feat: add percent input
g4rcez/the-mask-input pull request #40
Opened 2022-11-19 00:07 UTC by leoavelino7

2022-11-19 00:08 UTC, leoavelino7 commented on src/percent-input.tsx
> +		useEffect(() => {
Tentei fazer a mesma jogada que do Currency Input, mas não estava indo. 
Ai joguei nesse useEffect

@g4rcez

2022-11-19 00:09 UTC, leoavelino7 commented on src/percent-input.tsx
> +		useEffect(() => {
Ainda rola o problema de:
1 - Digitei algo
2 - Fui e coloquei o cursor depois do %
3 - Uso o apagar e ele não entende que deveria tentar apagar um valor

2022-11-28 14:38 UTC, g4rcez requested changes

2022-11-28 14:38 UTC, g4rcez commented on src/percent-input.tsx
> +		currency: CurrencyCode;
Percentual não tem currencyCode, podemos matar esse cara

2022-11-28 14:38 UTC, g4rcez commented on src/percent-input.tsx
> +			() => setInput(html.value === "" ? "" : toPercent(Number.parseFloat(`${html.value ?? "0"}`).toFixed(info.fraction.length), info)),
Pra simplificar, é válido tratar assim
```suggestion
			() => setInput(html.value || toPercent(Number.parseFloat(`${html.value ?? "0"}`).toFixed(info.fraction.length), info)),
```

2022-11-28 14:38 UTC, g4rcez commented on src/percent-input.tsx
> +		const focusNumber = () => {
Como essa função é usada no keyUp, acho válido subir ela nos componentes

2022-11-28 14:38 UTC, g4rcez commented on src/percent-input.tsx
> +				const { selectionStart, selectionEnd } = event.currentTarget;
```suggestion
			const target = event.currentTarget;
			if (target.selectionStart !== null) {
				const { selectionStart, selectionEnd } = target;
```

2022-12-12 21:56 UTC, leoavelino7 commented on src/percent-input.tsx
> +		const focusNumber = () => {
Não entendi essa :cry:

2022-12-19 05:42 UTC, g4rcez commented on src/percent-input.tsx
> +		const focusNumber = () => {
Subir de posição no código mesmo, pra ficar mais C style no código

2022-12-29 03:52 UTC, g4rcez approved these changes

2022-12-29 13:28 UTC, merged